### ISSUE TITLE
Switch web app to receive unit list from Firebase and populate location options in left menu

### ISSUE THREAD

**Issue by JaxonWright** [Passageway/PassagewayWeb#2]

**Comment by ChadTeitsma** [comment]
Potentially load all data upon initial loading of the site. Or have some way of caching the data so you are not querying for all data each time a location is selected

**Comment by TimJung** [comment]
Blueprints included in Firebase storage.

**Comment by jocmp** [comment]
Fixed with 85b557b077fe46d081a2bfdb2440944c4a987097
